client_id = "8ae407b750e150c37441496b596fdb0e"
name = "Announcement App"
handle = "announcement-app"

application_url = "https://shopify-api-service.onrender.com"
embedded = true

[auth]
redirect_urls = [
  "https://shopify-api-service.onrender.com/api/auth/callback"
]

[web.backend]
command = "npm start"
cwd = "backend"

[web.frontend]
command = "npm run build"
cwd = "frontend"

[access_scopes]
scopes = "write_products,read_metafields,write_metafields"
